export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
export const ADD_TODO_LOADING = "ADD_TODO_LOADING";
export const ADD_TODO_ERROR = "ADD_TODO_ERROR";
export const DEL_TODO = "DEL_TODO";

export const EDIT_TITLE_SUCCESS = "EDIT_TITLE_SUCCESS";
export const EDIT_TITLE_ERROR = "EDIT_TITLE_ERROR";
export const EDIT_TITLE_LOADING = "EDIT_TITLE_LOADING";

export const TOGGLE_TODO_SUCCESS = "TOGGLE_TODO_SUCCESS";
export const TOGGLE_TODO_LOADING = "TOGGLE_TODO_LOADING";


export const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS";
export const DELETE_TODO_LOADING = "DELETE_TODO_LOADING";