
export const TOGGLE_TODO_STATUS = "TOGGLE_TODO_STATUS";
export const REMOTE_TODO = "REMOVE_TODO";

export const ADD_TOTAL = "ADD_TOTAL";
export const INC_COMPLETED = "INC_COMPLETED";
export const DEC_COMPLETED = "DEC_COMPLETED";

export const UPDATE_TODO = "UPDATE_TODO";

export const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
export const ADD_TODO_ERROR = "TOGGLE_ERROR";
export const ADD_TODO_LOADING = "TOGGLE_LOADING"; 

export const GET_TODO_SUCCESS = "GET_TODO_SUCCESS";
export const GET_TODO_ERROR = "GET_TODO_ERROR";
export const GET_TODO_LOADING = "GET_TODO_LOADING"; 

export const EDIT_TITLE_SUCCESS = "EDIT_TITLE_SUCCESS";
export const EDIT_TITLE_ERROR = "EDIT_TITLE_ERROR";
export const EDIT_TITLE_LOADING = "EDIT_TITLE_LOADING";

export const TOGGLE_TODO_SUCCESS = "TOGGLE_TODO_SUCCESS";
export const TOGGLE_TODO_ERROR = "TOGGLE_TODO_ERROR";
export const TOGGLE_TODO_LOADING = "TOGGLE_TODO_LOADING";

export const REMOVE_TODO_SUCCESS = "REMOVE_TODO_SUCCESS";
export const REMOVE_TODO_ERROR = "REMOVE_TODO_ERROR";
export const REMOVE_TODO_LOADING = "REMOVE_TODO_LOADING";